version: "3.9"

services:
  bot:
    build:
      context: .
    image: goodwin954/bot-survey
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: bot
      POSTGRES_DB: bot
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bot" ]
      interval: 5s
      timeout: 5s
      retries: 5
